# Generated by Django 5.0.2 on 2026-09-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'houses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('houses', models.ManyToManyField(related_name='users', to='api.house')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
