# Generated by Django 5.0.2 on 2026-09-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_first_name', models.CharField(max_length=255)),
                ('user_last_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_street_address', models.CharField(max_length=255)),
                ('house_suburb', models.CharField(max_length=255)),
                ('house_postcode', models.CharField(max_length=20)),
                ('house_state', models.CharField(max_length=255)),
                ('house_country', models.CharField(max_length=255)),
                ('house_admins', models.ManyToManyField(related_name='administered_houses', to='api.user')),
                ('house_users', models.ManyToManyField(related_name='houses', to='api.user')),
            ],
            options={
                'db_table': 'houses',
            },
        ),
    ]
