# Generated by Django 5.0.2 on 2026-09-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='houses',
            field=models.ManyToManyField(related_name='occupants', to='api.house'),
        ),
    ]
