# Generated by Django 5.0.2 on 2026-09-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_houses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='houses',
            field=models.ManyToManyField(related_name='users', to='api.house'),
        ),
    ]
