apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.backend.name }}-service
    labels:
        app: {{ .Values.backend.name }}
spec:
    type: {{ .Values.backend.service.type }}
    selector:
        app: {{ .Values.backend.name }}
    ports:
{{- toYaml .Values.backend.service.ports | nindent 8 }}