AWSTemplateFormatVersion: '2010-09-09'
Description: cognito user pool

Parameters:
  App:
    Type: String
    Default: roommate
  
  Env:
    Type: String
  
  DomainName:
    Type: String
  
  GoogleClientId:
    Type: String
    NoEcho: true
  
  GoogleClientSecret:
    Type: String
    NoEcho: true

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${App}-users-${Env}
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${App}-auth-${Env}
      UserPoolId: !Ref UserPool

  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: openid email profile
      AttributeMapping:
        email: email
        name: name
        picture: picture

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: GoogleIdentityProvider
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: alb-client
      GenerateSecret: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      CallbackURLs:
        - !Sub https://${DomainName}/oauth2/idpresponse
      LogoutURLs:
        - !Sub https://${DomainName}/logout
      SupportedIdentityProviders:
        - COGNITO
        - Google

Outputs:
  UserPoolId:
    Description: user pool id
    Value: !Ref UserPool
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolId"

  UserPoolArn:
    Description: user pool arn
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolArn"

  UserPoolClientId:
    Description: user pool client id
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolClientId"

  UserPoolDomainUrl:
    Description: hosted user pool ui domain
    Value: !Sub "https://${App}-auth-${Env}.auth.${AWS::Region}.amazoncognito.com"
  
  UserPoolDomainPrefix:
    Description: hosted user pool ui domain prefix
    Value: !Sub "${App}-auth-${Env}"