AWSTemplateFormatVersion: "2010-09-09"
Description: eks cluster deployment

Parameters:
  App:
    Type: String
    Default: roommate

  Env:
    Type: String
    AllowedValues:
      - Prod
      - Dev
    Default: Dev

  NetworkStackName:
    Type: String
    Description: name of the network stack

  KubernetesVersion:
    Type: String
    Default: "1.33"

  NodeInstanceType:
    Type: String
    Default: t3.medium

  NodeDesiredSize:
    Type: Number
    Default: 1

  NodeMinSize:
    Type: Number
    Default: 1

  NodeMaxSize:
    Type: Number
    Default: 2

Resources:
  # iam roles
  EksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${App}-eks-cluster-role-${Env}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${App}-node-role-${Env}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  # eks cluster
  EksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub "${App}-eks-cluster-${Env}"
      Version: !Ref KubernetesVersion
      RoleArn: !GetAtt EksClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateSubnet1Id"
          - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateSubnet2Id"
          - Fn::ImportValue: !Sub "${NetworkStackName}-PublicSubnet1Id"
          - Fn::ImportValue: !Sub "${NetworkStackName}-PublicSubnet2Id"
        EndpointPublicAccess: true
        EndpointPrivateAccess: true

  # eks node group
  ManagedNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EksCluster
      NodegroupName: !Sub "${App}-eks-node-group-${Env}"
      NodeRole: !GetAtt NodeInstanceRole.Arn
      Subnets:
        - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateSubnet1Id"
        - Fn::ImportValue: !Sub "${NetworkStackName}-PrivateSubnet2Id"
      InstanceTypes:
        - !Ref NodeInstanceType
      ScalingConfig:
        MinSize: !Ref NodeMinSize
        DesiredSize: !Ref NodeDesiredSize
        MaxSize: !Ref NodeMaxSize
      AmiType: AL2_x86_64

Outputs:
  ClusterName:
    Value: !Ref EksCluster
  ClusterArn:
    Value: !GetAtt EksCluster.Arn
  ClusterEndpoint:
    Value: !GetAtt EksCluster.Endpoint
  ClusterSecurityGroupId:
    Value: !GetAtt EksCluster.ClusterSecurityGroupId