AWSTemplateFormatVersion: "2010-09-09"
Description: s3 bucket for lambda deployment packages

Parameters:
  App:
    Type: String
    Default: roommate

  Env:
    Type: String
    AllowedValues:
      - prod
      - dev
    Default: dev

Resources:
  LambdaArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${App}-lambda-artifacts-${Env}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  BucketName:
    Value: !Ref LambdaArtifactsBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
